spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Rownsdn91@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
