spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
#    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Rownsdn91@
logging:
  level:
#    root: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
