package net.fashiongo.api.vendor_onboarding.model.entity;

public enum DocumentType {

    COMPLETED_AND_SIGNED,
    TAXPAYER_ID,
    BANK_ACCOUNT_VERIFICATION,
    STATE_ISSUED_BUSINESS_LICENSE_OR_SELLER_PERMIT,
    IMAGES_OF_SWEN_IN_LABELS,
    ADDITIONAL_DOCUMENT_1,
    ADDITIONAL_DOCUMENT_2

}
