### metrics 정보 확인
GET http://localhost:8080/actuator/metrics
Accept: application/json

### request 정보 확인
GET http://localhost:8080/actuator/metrics/http.server.requests
Accept: application/json


### actuator 정보 확인
GET http://localhost:8080/actuator
Accept: application/json


### JVM 정보 확인
GET http://localhost:8080/actuator/metrics/jvm.info
Accept: application/json


### test api
GET http://localhost:8080/log
Accept: application/json

### cpu test api
GET http://localhost:8080/cpu
Accept: application/json