spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kakaopay_settlement?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Rownsdn91@
    hikari:
      maximum-pool-size: 10

springdoc:
  swagger-ui:
    path: /api-docs

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080
